# Generated by Django 4.1.2 on 2022-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercisename', models.CharField(max_length=100)),
                ('exerciseimg', models.ImageField(upload_to='exercise_pics')),
                ('exercisesteps', models.TextField()),
                ('exercisedetails', models.TextField()),
                ('exercisenoOfmins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=100)),
                ('recipeimg', models.ImageField(upload_to='recipes_pics')),
                ('recipesteps', models.TextField()),
                ('recipedetails', models.TextField()),
                ('recipesnoOfmins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoganame', models.CharField(max_length=100)),
                ('yogaimg', models.ImageField(upload_to='yoga_pics')),
                ('yogasteps', models.TextField()),
                ('yogadetails', models.TextField()),
                ('yoganoOfmins', models.IntegerField()),
            ],
        ),
    ]
